# Generated by Django 2.2 on 2020-03-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profilefeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeed',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
